apiVersion: v1
kind: Service
metadata:
  labels:
    run: <name>
  name: <name>
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: <name>
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: <name>
  name: <name>
spec:
  replicas: 3
  selector:
    matchLabels:
      run: <name>
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: <name>
    spec:
      containers:
      - image: <fullImageName>
        imagePullPolicy: Always
        name: <name>
        resources:
          limits:
            memory: 200Mi
            cpu: "0.4" 
