# see https://helm.sh/docs/howto/charts_tips_and_tricks/ (section "Creating Image Pull Secrets")
apiVersion: v1
kind: Secret
metadata:
  name: mypullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}